env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  "react/react-in-jsx-scope": off
  "no-case-declarations": off
  "no-unused-vars": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-unused-vars": off
settings:
  react:
    version: "18.2.0"
